### ISSUE TITLE
Adding `--force` does not work due to directory already existing

### ISSUE THREAD

**Issue by onedr0p** [mirkolenz/makejinja#98]
**Describe the bug**

Adding `--force` does not work due to directory already existing from a previous `makejinja --force` execution

**To Reproduce**

## command

```sh
makejinja --force
```

## config

```toml
[makejinja]
inputs = ["./bootstrap/templates"]
output = "./"
data = ["./bootstrap/vars/addons.yaml", "./bootstrap/vars/config.yaml"]
import_paths = ["./bootstrap/scripts"]
loaders = ["loader:Loader"]
jinja_suffix = ".j2"

# Block delimiters are changed to avoid conflicts with Renovate
# https://github.com/renovatebot/renovate/discussions/18470
[makejinja.delimiter]
block_start = "#%"
block_end = "%#"
comment_start = "{#"
comment_end = "#}"
variable_start = "{%"
variable_end = "%}"
```

## error

```
Load data '/Users/devin/Code/repos/onedr0p/flux-template-cluster/bootstrap/vars/addons.yaml'
Load data '/Users/devin/Code/repos/onedr0p/flux-template-cluster/bootstrap/vars/config.yaml'
Render file '/Users/devin/Code/repos/onedr0p/flux-template-cluster/bootstrap/templates/.sops.yaml.j2' -> '/Users/devin/Code/repos/onedr0p/flux-template-cluster/.sops.yaml'
Create folder '/Users/devin/Code/repos/onedr0p/flux-template-cluster/bootstrap/templates/ansible' -> '/Users/devin/Code/repos/onedr0p/flux-template-cluster/ansible'
Traceback (most recent call last):
  File "/Users/devin/Code/repos/onedr0p/flux-template-cluster/.venv/bin/makejinja", line 8, in <module>
    sys.exit(makejinja_cli())
             ^^^^^^^^^^^^^^^
  File "/Users/devin/Code/repos/onedr0p/flux-template-cluster/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/devin/Code/repos/onedr0p/flux-template-cluster/.venv/lib/python3.11/site-packages/rich_click/rich_command.py", line 126, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/devin/Code/repos/onedr0p/flux-template-cluster/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/devin/Code/repos/onedr0p/flux-template-cluster/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/devin/Code/repos/onedr0p/flux-template-cluster/.venv/lib/python3.11/site-packages/typed_settings/cli_click.py", line 247, in new_func
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/devin/Code/repos/onedr0p/flux-template-cluster/.venv/lib/python3.11/site-packages/makejinja/cli.py", line 37, in makejinja_cli
    makejinja(config)
  File "/Users/devin/Code/repos/onedr0p/flux-template-cluster/.venv/lib/python3.11/site-packages/makejinja/app.py", line 59, in makejinja
    handle_input_folder(
  File "/Users/devin/Code/repos/onedr0p/flux-template-cluster/.venv/lib/python3.11/site-packages/makejinja/app.py", line 155, in handle_input_folder
    output_path.mkdir()
  File "/opt/homebrew/Cellar/python@3.11/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pathlib.py", line 1116, in mkdir
    os.mkdir(self, mode)
FileExistsError: [Errno 17] File exists: '/Users/devin/Code/repos/onedr0p/flux-template-cluster/ansible'
task: Failed to run task "configure": exit status 1
```

**Expected behavior**

That adding `--force` will not fail if the directory already exists.

**Comment by onedr0p** [comment]
I also wanted to say that I cannot use `--clean` as the output directory includes files/folders outside what gets rendered.

**Comment by mirkolenz** [comment]
Thanks for the report! At the moment, `--force` is only applied to files and not folders (I mostly use makejinja with the `--clean` flag myself). I just pushed a commit fixing this bug, as soon as CI is finished (typically a few minutes) a new release will be pushed to PyPI.

**Comment by mirkolenz** [comment]
Thanks for your kind offer, I'm glad that makejinja is helpful! No need for money though, spreading the word about the project is support enough. Also keep reporting any issues you may find, this can only be beneficial for makejinja. Really appreciate your enthusiasm 😄
